let data,view='overview',query='';
const $=id=>document.getElementById(id), esc=v=>String(v??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(n,d=2)=>Number.isFinite(n)?n.toLocaleString('sv-SE',{minimumFractionDigits:d,maximumFractionDigits:d}):'—';
const usd=n=>Number.isFinite(n)?'$ '+fmt(n):'—',pct=n=>Number.isFinite(n)?(n>0?'+':'')+fmt(n)+' %':'—',color=n=>n>0?'positive':n<0?'negative':'';
const when=s=>s?new Date(/[zZ]|[+-]\d\d:\d\d$/.test(s)?s:s+'Z').toLocaleString('sv-SE',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}):'Datum saknas';
const safe=url=>{try{let u=new URL(url);return ['http:','https:'].includes(u.protocol)?esc(u.href):'#'}catch{return '#'}};
const name=t=>data.names[t]||t, match=t=>(t+' '+name(t)).toLowerCase().includes(query);
function chart(points,small=false){let values=points.map(p=>p[1]).filter(Number.isFinite);if(values.length<2)return '<div class="empty">Graf visas när minst två observationer finns.</div>';let min=Math.min(...values),max=Math.max(...values),span=max-min||Math.abs(max)*.01||1,w=small?100:700,h=small?30:180,pad=small?3:12;let coords=values.map((v,i)=>`${pad+i*(w-2*pad)/(values.length-1)},${h-pad-(v-min)/span*(h-2*pad)}`).join(' ');let stroke=values.at(-1)>=values[0]?'#159980':'#c55e70';return `${small?'':`<div class="chart-footer"><span>Min ${fmt(min)}</span><span>Max ${fmt(max)}</span></div>`}<svg class="${small?'spark':'chart'}" viewBox="0 0 ${w} ${h}" preserveAspectRatio="none" role="img" aria-label="${small?'Kursutveckling':'Värdeutveckling'}">${small?'':`<path d="M${pad} ${h*.25} H${w-pad} M${pad} ${h*.55} H${w-pad} M${pad} ${h*.85} H${w-pad}" stroke="#edf0f5" fill="none"/>`}<polyline points="${coords}" stroke="${stroke}" stroke-width="${small?1.7:2.5}" fill="none" vector-effect="non-scaling-stroke"/></svg>`}
function company(t){return `<div class="company"><span class="avatar">${esc(t.slice(0,2))}</span><div><b>${esc(t)}</b><small>${esc(name(t))}</small></div></div>`}
function badge(s){return `<span class="tag ${s?.includes('BUY')?'buy':s?.includes('SELL')?'sell':''}">${s?.includes('BUY')?'Köp':s?.includes('SELL')?'Sälj':s==='NO TRADE'?'Avvaktar':s==='HOLD'?'Behåll':esc(s||'Data saknas')}</span>`}
function metric(label,value,note,cls=''){return `<div class="metric"><div class="metric-label">${label}<span>↗</span></div><strong class="${cls}">${value}</strong><small>${note}</small></div>`}
function pricesTable(symbols){return `<div class="table-wrap"><table><thead><tr><th>Bolag</th><th>Kurs</th><th>Idag*</th><th>5 dagar</th><th>Botens beslut</th></tr></thead><tbody>${symbols.filter(match).map(t=>{let q=data.quotes[t]||{};return `<tr class="stock-row" data-stock="${esc(t)}"><td>${company(t)}</td><td>${fmt(q.native_price)} <small>${esc(q.quote_currency||'')}</small></td><td class="${color(q.daily_change_pct)}">${pct(q.daily_change_pct)}</td><td>${q.history?.length>1?chart(q.history,true):'—'}</td><td>${badge(data.decisions[t]?.action)}</td></tr>`}).join('')}</tbody></table></div>`}
function newsList(items,limit=6){return items.slice(0,limit).map(a=>`<article class="news-item"><div class="news-meta"><span>${esc(a.provider||'Nyhet')}</span><span>· ${when(a.published_at)}</span></div><a href="${safe(a.url)}" target="_blank" rel="noopener noreferrer">${esc(a.title)} ↗</a><div class="news-meta">${(a.tickers||[]).map(t=>`<span class="tag">${esc(t)}</span>`).join('')}<span>${a.origin==='bot_research'?'I botens analys':'Ny rubrik · ej analyserad av modellen'}</span></div></article>`).join('')||'<div class="empty">Inga verifierbart kopplade nyheter i den här uppdateringen.</div>'}
function holdings(){return `<div class="table-wrap"><table><thead><tr><th>Innehav</th><th>Antal</th><th>Värde USD</th><th>Orealiserat USD</th><th>Kurstid</th></tr></thead><tbody>${data.positions.filter(p=>match(p.ticker)).map(p=>`<tr class="stock-row" data-stock="${esc(p.ticker)}"><td>${company(p.ticker)}</td><td>${fmt(p.qty,3)}</td><td>${usd(p.value)}</td><td class="${color(p.pnl)}">${usd(p.pnl)}</td><td>${when(data.quotes[p.ticker]?.quote_time)}</td></tr>`).join('')}</tbody></table></div>`}
function transactions(limit=Infinity){return `<div class="table-wrap"><table><thead><tr><th>Tid</th><th>Aktie</th><th>Affär</th><th>Antal</th><th>Belopp USD</th><th>Strategi</th><th>Realiserat USD</th></tr></thead><tbody>${[...data.trades].reverse().filter(t=>match(t.ticker)).slice(0,limit).map(t=>`<tr class="stock-row" data-stock="${esc(t.ticker)}"><td>${when(t.time)}</td><td><b>${esc(t.ticker)}</b></td><td>${badge(t.action)}</td><td>${fmt(t.qty,3)}</td><td>${usd(t.amount??t.qty*t.price)}</td><td>${esc(strategy(t.strategy))}</td><td class="${color(t.realized_pnl)}">${usd(t.realized_pnl)}</td></tr>`).join('')}</tbody></table></div>`}
function strategy(s){return ({trend_following:'Trendföljning',mean_reversion:'Återgång till medelvärdet',momentum:'Momentum',breakout:'Utbrott',earnings:'Rapportdriven'})[s]||s||'—'}
function render(){let value=data.account_value,pnl=Number.isFinite(value)?value-data.starting_cash:null;let realized=data.trades.reduce((s,t)=>s+(t.realized_pnl||0),0);$('metrics').innerHTML=metric('Portföljvärde',usd(value),'Innehav + tillgängliga låtsaspengar')+metric('Sedan start',usd(pnl),pct(Number.isFinite(pnl)?pnl/data.starting_cash*100:null),color(pnl))+metric('Tillgängligt kapital',usd(data.cash),'USD · simulerad kassa')+metric('Aktiva innehav',String(data.positions.length),`${data.trades.length} affärer · ${usd(realized)} realiserat`);
 let labels={overview:'Översikt',portfolio:'Portfölj',watchlist:'Bevakning',trades:'Affärer',news:'Nyhetsflöde',learning:'Modell & lärande',themes:'Framtida marknader'};$('page-name').textContent=labels[view];$('title').textContent=view==='overview'?'Marknaden, genom botens ögon.':labels[view];$('tabs').innerHTML=`<h2>${view==='overview'?'Din marknadsöversikt':labels[view]} <span class="count">${view==='watchlist'?data.watchlist.length+' bolag':''}</span></h2>`;
 let news=data.news.filter(a=>!query||(a.title+' '+(a.tickers||[]).join(' ')).toLowerCase().includes(query));let watched=data.watchlist.map(w=>w.ticker);
 if(view==='overview')$('content').innerHTML=`<div class="grid"><div><div class="card"><div class="card-head"><h2>Kontots utveckling</h2><span class="pill">BOTENS RAPPORTER</span></div><div class="chart-label">USD · sparade kontovärden vid botkörningar</div>${chart(data.account_history.map(p=>[p.time,p.value]))}<div class="chart-footer"><span>${when(data.account_history[0]?.time)}</span><span>${when(data.account_history.at(-1)?.time)}</span></div></div><div class="card"><div class="card-head"><h2>Din särskilda bevakning</h2><span class="pill">INFÖR RAPPORT</span></div>${pricesTable(watched)}<div class="note">Klicka på ett bolag för kursgraf, strategier och bolagskontroll. *Förändring mot föregående tillgängliga handelsdags sista 5-minuterskurs.</div></div></div><div><div class="card"><div class="card-head"><h2>Nyheter som rör boten</h2><span class="pill">${news.length} RUBRIKER</span></div>${newsList(news,4)}</div><div class="card"><div class="card-head"><h2>Senaste beslut</h2></div><div class="mini-list">${[...data.trades].reverse().slice(0,4).map(t=>`<div><span><b>${esc(t.ticker)}</b><br><small>${strategy(t.strategy)}</small></span><span>${badge(t.action)}<br><small>${usd(t.amount)}</small></span></div>`).join('')}</div></div></div></div><div class="card"><div class="card-head"><h2>Innehaven just nu</h2><span class="pill">${data.positions.length} POSITIONER</span></div>${holdings()}</div>`;
 if(view==='portfolio')$('content').innerHTML=`<div class="card"><div class="card-head"><h2>Alla öppna positioner</h2></div>${holdings()}<p class="note">Orealiserat resultat jämför kursvärdet med kvarvarande inköpskostnad i USD. Valutaförändringar ingår. Avgifter och slippage ingår inte.</p></div>`;
 if(view==='watchlist')$('content').innerHTML=`<div class="card">${pricesTable(watched)}</div><div class="card"><h2>Övriga analyserade aktier</h2>${pricesTable(Object.keys(data.decisions).filter(t=>!watched.includes(t)))}</div>`;
 if(view==='trades')$('content').innerHTML=`<div class="card"><div class="card-head"><h2>Alla simulerade affärer</h2><a href="trades.csv">Exportera CSV ↗</a></div>${transactions()}</div>`;
 if(view==='news')$('content').innerHTML=`<div class="note">Nyheter matchas mot bolagsnamn eller ticker. Nya rubriker uppdaterar inte botens köpbeslut och har inte automatiskt analyserats av FinBERT. Källan öppnas när du klickar.</div><div class="news-grid">${news.length?news.map(a=>`<div class="card">${newsList([a],1)}</div>`).join(''):'<div class="empty">Inga matchande nyheter.</div>'}</div>`;
 if(view==='themes'){let t=data.long_term_analysis;$('content').innerHTML=t?`<div class="note">${esc(t.policy)}<br>${esc(t.source_policy)}</div><div class="grid">${t.themes.map(x=>`<div class="card"><h2>${esc(x.name)}</h2><p>${esc(x.observation)}</p><h3>Utsikter till ${x.horizon_end}</h3><p>${esc(x.forecast)}</p><p class="note">${esc(x.risks)}</p><a href="${safe(x.url)}" target="_blank" rel="noopener">${esc(x.publisher)} ↗</a><p>Kontrollerad ${esc(x.reviewed)} ${x.needs_source_review?'· Behöver uppdateras':''} ${x.forecast_expired?'· Prognos utgången':''}</p></div>`).join('')}</div><div class="card"><h2>Bolagens koppling till tillväxten</h2><p>${t.coverage.with_profile} av ${t.coverage.analyzed} bolag har verksamhetsbeskrivning. Nyckelord visar möjliga kopplingar, inte verifierade intäkter.</p>${Object.entries(t.companies).filter(([symbol])=>match(symbol)).map(([symbol,c])=>`<div class="detail-reason"><b>${esc(symbol)}</b> · ${esc(c.matches.map(m=>t.themes.find(x=>x.id===m.theme_id)?.name).join(', ')||'Ingen verifierad koppling')}<p>${esc(c.assessment)}</p><small>P/E framåt: ${fmt(c.checks.forward_pe)} · Fritt kassaflöde: ${fmt(c.checks.free_cash_flow)} ${esc(c.checks.financial_currency||'')} · Skuld/eget kapital (Yahoo): ${fmt(c.checks.debt_to_equity)}</small><p class="note">Saknas: ${esc(c.missing.join('; '))}</p></div>`).join('')}</div>`:'<div class="card">Den här äldre botrapporten saknar långsiktig analys. Visas efter en körning med den nya versionen.</div>';}
 if(view==='themes')$('content').innerHTML+=catalogueView();
 if(view==='learning')$('content').innerHTML=learningView();
 document.querySelectorAll('[data-stock]').forEach(el=>el.onclick=()=>detail(el.dataset.stock));
 $('report-stamp').textContent='Botens senaste analys: '+when(data.report_time);
 const age=(Date.now()-new Date(data.updated_at))/60000;$('freshness').textContent='Data hämtad '+when(data.updated_at);
 let notices=[];if(age>45)notices.push('Uppdateringen är äldre än 45 minuter. Visar senast tillgängliga data.');if(data.valuation_mixed)notices.push('Vissa innehav värderas med äldre botkurser.');if(data.issues.length)notices.push(`${data.issues.length} hämtningar saknade nya data. Bolagsvyn visar kursens tid och eventuella fel.`);$('notice').textContent=notices.join(' ');
}
function detail(t){let q=data.quotes[t]||{},d=data.decisions[t]||{},r=data.research[t]||{},w=data.watchlist.find(w=>w.ticker===t);let f=r.financials||{},a=r.analysts||{};$('detail-content').innerHTML=`<div class="eyebrow">${esc(t)} · ${esc(q.quote_currency||'')}</div><h2>${esc(name(t))}</h2><p>Kurstid: ${when(q.quote_time)} · ${q.status==='provider_quote'?'Yahoo · kan vara fördröjd':'Botens äldre rapportsnapshot'}</p><div class="metrics">${metric('Senaste kurs',fmt(q.native_price),esc(q.quote_currency||''))}${metric('Förändring idag*',pct(q.daily_change_pct),'Mot föregående handelsdag',color(q.daily_change_pct))}</div>${chart(q.history||[])}${q.error?`<div class="note">Kursuppdatering misslyckades: ${esc(q.error)}</div>`:''}<h3>Botens beslut ${badge(d.action)}</h3><p class="detail-reason">${esc(d.error||d.reason||'Ingen bedömning tillgänglig')}</p><p class="note">${esc(r.gate?.reason||'Bolagskontroll saknas')}</p><h3>De fem strategierna</h3>${Object.entries(d.strategies||{}).map(([k,v])=>`<p class="detail-reason"><b>${strategy(k)} · ${v.entry?'Köpregel uppfylld':'Ingen köpsignal'}</b><br>${esc(v.reason)}</p>`).join('')}<h3>Bolagsdata</h3><div class="mini-list"><div><span>Finansiell period</span><b>${when(f.period_end)}</b></div><div><span>Omsättningstillväxt, år/år</span><b>${pct(Number.isFinite(f.revenue_yoy_growth)?f.revenue_yoy_growth*100:null)}</b></div><div><span>Nettovinsttillväxt, år/år</span><b>${pct(Number.isFinite(f.net_income_yoy_growth)?f.net_income_yoy_growth*100:null)}</b></div><div><span>Analytikernas mål, uppsida*</span><b>${pct(Number.isFinite(a.target_upside)?a.target_upside*100:null)}</b></div><div><span>Nästa rapport enligt Yahoo</span><b>${when(r.earnings?.next_report)}</b></div></div><div class="note">Rapportdatum är inte bolagsbekräftade och avser inte nödvändigtvis Q4. Analytikermål är vanligen cirka 12 månader. Uppgifterna ovan hämtades vid botkörningen ${when(data.report_time)}.</div>${investmentView(t)}${w?`<a href="${safe(w.ir_url)}" target="_blank" rel="noopener">Bolagets investerarsida ↗</a>`:''}<h3>Relaterade nyheter</h3>${newsList(data.news.filter(a=>(a.tickers||[]).includes(t)),8)}`;$('detail').showModal()}
async function load(){try{$('refresh').disabled=true;const response=await fetch('data.json?t='+Date.now(),{cache:'no-store'});if(!response.ok)throw Error(response.status);let incoming=await response.json();if(!incoming.quotes||!incoming.positions)throw Error('Ogiltig data');data=incoming;render()}catch(e){$('notice').textContent='Kunde inte hämta nya data. '+(data?'Senaste inlästa värden visas.':'Försök igen om en stund.')}finally{$('refresh').disabled=false}}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{view=b.dataset.view;document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x===b));if(data)render()});$('search').oninput=e=>{query=e.target.value.toLowerCase();if(data)render()};$('refresh').onclick=load;$('close-detail').onclick=()=>$('detail').close();$('detail').onclick=e=>{if(e.target===$('detail'))$('detail').close()};load();setInterval(load,60000);

function catalogueView(){let c=data.industry_catalogue;if(!c)return '';let q=query.toLowerCase();let rows=c.entries.filter(x=>x.name.toLowerCase().includes(q)||c.matches.some(m=>m.industry===x.name&&match(m.ticker)));return `<div class="card"><h2>Branscher att undersöka</h2><a href="industry_growth_audit.json">Hämta hela källgranskningen ↗</a><p class="note">${esc(c.policy)}</p><p>${c.coverage.registered} områden · ${c.coverage.sourced_forecasts} källbelagda prognoser · övriga ej färdigverifierade · ${c.coverage.with_profile}/${c.coverage.companies} bolag med beskrivning. Kopplingar uppdateras vid botkörningar. Källkontroll sker inte automatiskt.</p><div class="table-wrap"><table><thead><tr><th>Område</th><th>Användarens antagande*</th><th>Möjliga bolagskopplingar</th><th>Underlag</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.name)}</td><td>${fmt(x.supplied_growth_assumption*100)} %</td><td>${esc(c.matches.filter(m=>m.industry===x.name).map(m=>m.ticker).join(', ')||'Ingen textträff i tillgängliga beskrivningar')}</td><td>${esc(x.review_note||'Ej verifierat')}${(x.forecast_candidates||[]).map(f=>`<p><a href="${safe(f.url)}" target="_blank" rel="noopener">${esc(f.subject)} ↗</a>: ${fmt(f.reported_cagr*100)} % CAGR 2026–2031<br><small>${f.arithmetic_consistent?'CAGR stämmer inom avrundning':'CAGR-konflikt'} · ${x.review_status==='sourced_forecast'?'Källbelagd prognos':'Ej godkänd prognos'}</small></p>`).join('')}</td></tr>`).join('')}</tbody></table></div><p class="note">*Originaltal från användaren. Jämförelsen avser global marknadsomsättning, årlig CAGR 2026–2031. Använd sökfältet för område eller bolag. Övriga områden kan sakna täckning; inga matchningar betyder inte att marknaden saknar potential.</p></div>`;}

function learningView(){
 const r=data.learning_results,l=data.learning||{};
 if(!r)return '<div class="card">Resultatvyn visas efter nästa webbuppdatering.</div>';
 const v=r.pattern_validation,change=r.training_loss_change_pct;
 const fit=r.training_fit==='worse'?'Sämre anpassning till träningsdata':r.training_fit==='better'?'Bättre anpassning till träningsdata':r.training_fit==='unchanged'?'Oförändrad anpassning':'Träningsjämförelse saknas';
 return `<div class="card"><h2>Ger boten resultat?</h2><p>Rapportens resultat den ${when(r.as_of)}. De aktuella kurserna högst upp kan ha ändrats sedan dess.</p><div class="metrics">${metric('Resultat sedan start',usd(r.total_pnl),pct(r.return_pct),color(r.total_pnl))}${metric('Avslutade försäljningar',String(r.sales),`${r.winning_sales} med vinst · ${r.losing_sales} med förlust`)}${metric('Säkrad vinst / förlust',usd(r.realized_pnl),'Realiserat i papperskontot',color(r.realized_pnl))}${metric('Öppna innehavs resultat',usd(r.unrealized_pnl),'Kan ändras innan försäljning',color(r.unrealized_pnl))}</div><p class="note">${r.sales===0?'Inga försäljningar ännu. Resultatet består av värdeförändringar i öppna innehav. ':''}Låtsaspengar, före avgifter och slippage. Portföljresultat visar inte ensamt att modellen blivit bättre. Ingen indexjämförelse finns ännu.</p></div>
 <div class="grid"><div class="card"><h2>Har pris-/volymmodellen blivit bättre?</h2><h3>Det är ännu inte visat.</h3><p>Rapporten saknar ett oberoende test av LSTM-modellens prognoser på nya utfall. Därför visas ingen påhittad träffsäkerhet.</p><h3>${fit}</h3><p>${Number.isFinite(change)?`Träningsfelet blev ${fmt(Math.abs(change))} % ${change>0?'större':change<0?'mindre':'förändrat'} på samma kontrollomgång med träningsdata.`:'Jämförbara träningsvärden saknas.'} Lägre fel är bättre på just dessa exempel, men säger inte hur nästa affär går.</p><p>${fmt(l.new_samples,0)} nya historiska träningsexempel · ${fmt(l.steps_this_run,0)} träningssteg. Fler exempel är aktivitet, inte bevis på bättre resultat.</p><details><summary>Visa tekniska träningsvärden</summary><p>Förlust före: ${fmt(l.fixed_batch_loss_before,4)} · efter: ${fmt(l.fixed_batch_loss_after,4)}. Detta är ett felmått, inte procent rätt eller avkastning.</p></details></div>
 <div class="card"><h2>Mönsterprognoser: vad blev utfallet?</h2><p>En separat jämförelse för mönsterbiblioteket, inte ett test av LSTM-modellen.</p>${v?`<div class="metrics">${metric('Färdiga utfall',fmt(v.settled,0),'Nuvarande utvärderingsprotokoll')}${metric('Väntar på utfall',fmt(v.pending,0),'21 handelsdagar efter ingångsobservation')}</div>${v.settled?`<p>Genomsnittligt prognosfel: ${fmt(v.mean_absolute_error*100)} procentenheter. Enkel historisk jämförelse: ${fmt(v.baseline_mean_absolute_error*100)} procentenheter. Lägre är bättre.</p>`:'<p>Inga färdiga utfall ännu. Väntande prognoser räknas inte som lyckade.</p>'}<p>${fmt(v.legacy_excluded||0,0)} prognoser från äldre protokoll är undantagna.</p>`:'<p>Ingen mönsterutvärdering finns i denna rapport.</p>'}<p class="note">Utfallen kan vara korrelerade. Mönsterresultat använder lokal valuta och en illustrativ kostnad på 0,2 %. De bevisar inte framtida lönsamhet.</p></div></div>
 <div class="card"><h2>Vilka strategier har tjänat pengar?</h2><div class="table-wrap"><table><thead><tr><th>Strategi</th><th>Försäljningar</th><th>Med vinst</th><th>Realiserat resultat</th></tr></thead><tbody>${r.strategies.map(x=>`<tr><td>${esc(strategy(x.strategy))}</td><td>${x.sales}</td><td>${x.sales?x.wins+' av '+x.sales:'Inga utfall ännu'}</td><td>${x.sales?usd(x.realized_pnl):'Ej utvärderbar'}</td></tr>`).join('')}</tbody></table></div><p>Strategierna styr köp tillsammans med bolagskontrollen. LSTM-poängen är diagnostisk. FinBERT analyserar nyhetstext med en fast förtränad modell.</p><a href="summary.md">Hela botrapporten ↗</a></div>`;
}

function investmentView(t){
 const a=data.investment_analysis,r=a?.companies?.[t];if(!r)return '';
 const show=v=>typeof v==='object'?JSON.stringify(v):String(v??'Saknas');
 return `<h3>Investeringsanalys: data, tes och motargument</h3><p class="note">${esc(a.policy)} Underlag från ${when(r.as_of)}. ${r.evidence_fresh?'':'Underlaget är gammalt eller saknar säkert datum.'}</p><p><b>${esc(r.assessment)}</b></p><p>Evidenskvalitet: ${esc(r.confidence)}. ${esc(r.confidence_reason)}</p><details open><summary>Från observation till investeringskonsekvens</summary>${Object.entries(r.chain).map(([k,v])=>`<p><b>${esc(({data:'Datareferenser',observation:'Observation',interpretation:'Tolkning',hypothesis:'Hypotes',scenario:'Scenario',investment_consequence:'Investeringskonsekvens'})[k])}</b><br>${esc(Array.isArray(v)?v.join(' · '):v)}</p>`).join('')}<p><b>Marknadens förväntningar:</b> ${esc(r.market_belief)}</p><p><b>Avvikande uppfattning:</b> ${esc(r.variant_perception)}</p></details><h3>Vad skulle en investerare med motsatt uppfattning säga?</h3>${r.counterarguments.map(x=>`<p class="detail-reason">${esc(x)}</p>`).join('')}<h3>Bull / base / bear</h3>${r.scenarios.map(x=>`<p class="detail-reason"><b>${esc(x.name)} · villkorat scenario</b><br>${esc(x.assumptions)}<br>Prövas genom: ${esc(x.trigger)}<br><small>${esc(x.reason_unquantified)}</small></p>`).join('')}<h3>Vad skulle försvaga tesen?</h3>${r.invalidation.map(x=>`<p>${esc(x.review_trigger)}</p>`).join('')}<h3>Nästa research som kan ändra slutsatsen</h3>${r.next_research.map(x=>`<p><b>${x.priority}. ${esc(x.question)}</b><br>${esc(x.decision_value)}</p>`).join('')}<details><summary>De nio analysområdena och vad som saknas</summary>${r.engines.map(x=>`<h4>${esc(x.name)} · ${x.status==='missing'?'Underlag saknas':'Delvis täckt'}</h4><p>Saknas: ${esc(x.missing.join('; '))}</p>`).join('')}</details><details><summary>Data, perioder och källor</summary>${r.facts.map(x=>`<p><b>${esc(x.label)}</b>: ${esc(show(x.value))} ${esc(x.unit||'')}<br>Period: ${esc(x.period||'Ej fastställd för detta snapshotmått')} · hämtat ${when(x.observed_at)}<br><a href="${safe(x.source)}" target="_blank" rel="noopener">Leverantörskälla ↗</a></p>`).join('')}<p>${esc(a.source_policy)}</p></details><details><summary>Tidshorisonter och portfölj</summary>${Object.entries(r.horizons).map(([k,v])=>`<p><b>${esc(k)}</b>: ${esc(v)}</p>`).join('')}<p>Vikt i rapportkontot: ${a.portfolio.positions[t]?(Number.isFinite(a.portfolio.positions[t].weight_of_account)?pct(a.portfolio.positions[t].weight_of_account*100):'Okänd – värdering saknas'):'Inget innehav'}</p><p>${esc(a.portfolio.basis)}</p></details>`;
}
